# Generated by Django 2.2.3 on 2019-10-19 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
