# Generated by Django 2.2.3 on 2019-10-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_otp_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
