# Generated by Django 2.2.3 on 2019-08-18 23:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    replaces = [('Project', '0001_initial'), ('Project', '0002_remove_logentry_level'), ('Project', '0003_auto_20190726_1803'), ('Project', '0004_auto_20190726_1804'), ('Project', '0005_auto_20190726_1805'), ('Project', '0006_auto_20190726_1806'), ('Project', '0007_auto_20190726_1822'), ('Project', '0008_logentry_created_at'), ('Project', '0009_exceptionstacktrace'), ('Project', '0010_logentry_tags')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionStackTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frames_data', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('log_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stacktrace', to='Project.LogEntry')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('level', models.IntegerField(choices=[(0, 'NOTSET'), (10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL'), (50, 'FATAL')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('tags', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name_plural': 'Log Entries',
            },
        ),
    ]
