# Generated by Django 2.2.3 on 2019-07-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_remove_logentry_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'verbose_name_plural': 'Log Entries'},
        ),
        migrations.AddField(
            model_name='logentry',
            name='level_name',
            field=models.CharField(choices=[('NOTSET', 0), ('DEBUG', 10), ('INFO', 20), ('WARNING', 30), ('ERROR', 40), ('CRITICAL', 50), ('FATAL', 50)], default=0, max_length=30),
            preserve_default=False,
        ),
    ]
