# Generated by Django 2.2.3 on 2019-10-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='secret_key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
