# Generated by Django 2.2.3 on 2019-07-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20190726_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='level_name',
            field=models.CharField(choices=[(0, 'NOTSET'), (10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL'), (50, 'FATAL')], max_length=30),
        ),
    ]
