# Generated by Django 2.2.3 on 2019-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_auto_20190726_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='level_name',
        ),
        migrations.AddField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'NOTSET'), (10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL'), (50, 'FATAL')], default=1),
            preserve_default=False,
        ),
    ]
