# Generated by Django 2.2.3 on 2019-07-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_auto_20190726_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='description',
            new_name='message',
        ),
    ]
