# Generated by Django 2.2.3 on 2019-08-08 16:46

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_logentry_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionStackTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frames_data', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('log_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stacktrace', to='Project.LogEntry')),
            ],
        ),
    ]
